name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Compile Java and JUnit tests
        run: |
          curl -L -o junit.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.2/junit-platform-console-standalone-1.10.2.jar
          find java -name "*.java" > sources.txt || true
          # Only compile if source files exist
          if [ -s sources.txt ]; then
            echo tests/JavaYearDecodingTest.java >> sources.txt
            javac -cp junit.jar @sources.txt
          fi

      - name: Run Java tests
        run: |
          if [ -f junit.jar ]; then
            # Run the JUnit Console against our compiled classes
            java -jar junit.jar -cp .:java --select-class tests.JavaYearDecodingTest
          else
            echo "No Java tests to run"
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Python tests
        run: |
          python3 --version
          python3 tests/test_year.py

